### ISSUE TITLE
Parameter problem

### ISSUE THREAD

**Issue by Junzizaiji** [mashaan14/PAtree-SGC#1]
Hello, about the function load_ There is a problem in dataset (). When using this function, an error load is reported_ Dataset () missing 1 required position argument: 'NumOfTrees', is the function parameter not comprehensive enough or I made some mistakes.

**Comment by mashaan14** [comment]
Hi,

sorry, the parameter `NumOfTrees` was missing when calling `load_dataset()` in the driver code `train.py`.
I fixed the function call, and it should work now.
